.TH internsctl 1 "January 2025" "internsctl v0.1.0" "User Commands"
.SH NAME
internsctl \- custom command for various server operations
.SH SYNOPSIS
.B internsctl
.RI [ options ] " command" " [parameters]"
.SH DESCRIPTION
The
.B internsctl
command provides various server operations such as fetching CPU and memory information, managing users, and retrieving file information.
.SH COMMANDS
.TP
.B cpu getinfo
Get CPU information.
.TP
.B memory getinfo
Get memory information.
.TP
.B user create <username>
Create a new user.
.TP
.B user list
List all regular users.
.TP
.B user list --sudo-only
List all users with sudo permissions.
.TP
.B file getinfo <file-name>
Get file information.
.TP
.B file getinfo [options] <file-name>
Get specific file information.
.SH OPTIONS
.TP
.BR \-\-help
Show help message.
.TP
.BR \-\-version
Show command version.
.SH EXAMPLES
.TP
.B internsctl cpu getinfo
Fetch CPU information.
.TP
.B internsctl memory getinfo
Fetch memory information.
.TP
.B internsctl user create john
Create a new user named 'john'.
.TP
.B internsctl user list
List all regular users.
.TP
.B internsctl file getinfo hello.txt
Get information about the file 'hello.txt'.
.SH AUTHOR
Developed by Rohit.

